### ISSUE TITLE
Incorporate method line number in eventHandler.facts

### ISSUE THREAD

**Issue by LuxiWang99** [izgzhen/markii#26]
Currently evenHandler.facts contains the method signature and the button ID. Providing the (OnClick) method line number makes the ui-reverse tool more useful. What is there that needs to be changed/added in order to make markii provide the (OnClick) method line number(the first line of implementation) in both settings: OnClick linked through XML and OnClick linked in Java using anonymous class.

**Comment by izgzhen** [comment]
Where the XML set handler facts are emitted:

https://github.com/izgzhen/markii/blob/32988821f025c8325e6c0e486cc3dfe23a2b9ea7/src/main/scala/com/research/nomad/markii/GUIAnalysis.scala#L167

Where the Java set handler facts are emitted:

https://github.com/izgzhen/markii/blob/32988821f025c8325e6c0e486cc3dfe23a2b9ea7/src/main/scala/com/research/nomad/markii/GUIAnalysis.scala#L360

**Comment by izgzhen** [comment]
I suggest you add a new fact `methodLineNumber(methodName, lineNo)` instead of appending to the existing facts. This minimizes the code changes for existing users, and also makes it more generic. (note that you can selectively emit facts about method line numbers -- that is, you don't have to emit line number for every method, you can just emit for ones you are interested).
